server:
  port: 9002


spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: rbac-provider
          uri: lb://RBAC-PROVIDER  #匹配后提供路由的服务地址
          predicates:
            - Path=/user/get/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
